apiVersion: v1
kind: Pod
metadata:
  name: eventhub-test
  namespace: otel-demo
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: python:3.11-slim
    command: ["/bin/bash"]
    args: 
    - -c
    - |
      pip install azure-eventhub[aio] &&
      python3 -c "
      import asyncio
      import json
      from azure.eventhub.aio import EventHubProducerClient
      from azure.eventhub import EventData
      
      async def send_test():
          conn_str = '$EVENTHUB_CONNECTION_STRING'
          hub_name = '$EVENTHUB_NAME'
          
          producer = EventHubProducerClient.from_connection_string(conn_str=conn_str, eventhub_name=hub_name)
          
          async with producer:
              test_order = {
                  'user_id': 'test-user-12345',
                  'order_id': 'test-order-67890', 
                  'timestamp': '2025-10-27T23:20:00Z',
                  'amount': 99.99,
                  'currency': 'USD'
              }
              
              batch = await producer.create_batch()
              batch.add(EventData(json.dumps(test_order)))
              await producer.send_batch(batch)
              print('✅ Successfully sent test message to EventHub!')
              print(f'📋 Message: {json.dumps(test_order, indent=2)}')
      
      print('🔄 Testing EventHub integration...')
      asyncio.run(send_test())
      print('✨ Test completed!')
      "
    env:
    - name: EVENTHUB_CONNECTION_STRING
      valueFrom:
        secretKeyRef:
          name: eventhub-secret
          key: connection-string
    - name: EVENTHUB_NAME
      value: otel-events